# NumPy Array Shape

**Get the Shape of an Array**

In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


Here the conclusions are:
1. (2,4) => 2 element in tuple, so the array has 2 dimensions.
2. 1st element is 2, so 2 elements are present in 1st dimension.
3. 2nd element in 4, so 4 elements are present in 2nd dimension

In [3]:
arr1=np.array([1,2,3,4],ndmin=5)
print(arr1)
print(arr1.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


# Numpy Array Reshape

**Reshape 1-D array into 2-D array**

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

**Reshape 1-D array into 3-D array**

In [5]:
newarr1=arr.reshape(2,3,2)
print(newarr1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
'''
newarr2=arr.reshape(3,3)
print(newarr2)
ValueError: cannot reshape array of size 12 into shape (3,3)
'''

'\nnewarr2=arr.reshape(3,3)\nprint(newarr2)\nValueError: cannot reshape array of size 12 into shape (3,3)\n'

**Returns Copy or View?**

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base) #Returns original array, so its a view

[1 2 3 4 5 6 7 8]


**Unknown Dimension**

In [11]:
newarr2=arr.reshape(2,-1,2) #-1 means unknown dimension.Numpy automatically calculates the value
print(newarr2)
print(newarr2.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


**Note**: We can not pass -1 to more than one dimension.

**Flattening the arrays**

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1) #converts multidimensional into 1-D array
print(newarr)
print(newarr.shape)

[1 2 3 4 5 6]
(6,)
