In [1]:
import numpy as np

# NumPy Creating Arrays

**Create a NumPy ndarray Object**

In [2]:
arr=np.array([1,2,3,4])

In [3]:
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


**Creating 0-D array**

In [4]:
arr0=np.array(43)

In [5]:
print(arr0)
print(arr0.ndim)

43
0


**Creating 1-D array**

In [7]:
arr1=np.array([1,2,3,4])

In [8]:
print(arr1)
print(arr1.ndim)

[1 2 3 4]
1


**Creating 2-D array**

In [11]:
arr2=np.array([[1,2,3],[4,5,6]])

In [13]:
print(arr2.ndim)
print(arr2)

2
[[1 2 3]
 [4 5 6]]


**Creating Higher Dimension Array**

In [20]:
arr3=np.array([1,2,3,4,7],ndmin=3)

In [21]:
print(arr3)
print(arr3.ndim)

[[[1 2 3 4 7]]]
3


arange() gives uncertain number of values based on steps

**Creation of an array with step size 1.33 between 0 - 10**

In [22]:
arange_arr=np.arange(0,10,1.33,dtype=np.float64)

In [23]:
print(arange_arr)

[0.   1.33 2.66 3.99 5.32 6.65 7.98 9.31]


Linespace asks for total number of values between 2 number

**Creation of an array with total 5 values between 0 - 160**

In [24]:
linespace_arr=np.linspace(0,160,5,dtype=np.float64)

In [25]:
print(linespace_arr)

[  0.  40.  80. 120. 160.]


# Array Indexing

In [27]:
print(arr[0]) #Accessing 1st element of arr

1


In [29]:
print(arr2[0,1]) #Accessing 2nd on 1st row

2


In [31]:
print(arr3[0,0,3]) #Accessing 4th element of 1st array of 1st array

4


In [33]:
print(arr2[1,-1]) #Accessing Last element of 2nd row

6
