# Array Slicing

In [1]:
import numpy as np

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [3]:
print(arr[4:])

[5 6 7]


In [4]:
print(arr[:4])

[1 2 3 4]


**Negative Slicing**

In [5]:
print(arr[-3:-1])

[5 6]


**Step**

In [6]:
print(arr[1::2])

[2 4 6]


**Slicing 2-D array**

In [7]:
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr1[1, 1:4]) #Return a list containing arr1[1,1],arr1[1,2] & arr1[1,3] as elements

[7 8 9]


In [8]:
print(arr1[0:2,1]) #Return a list containing arr1[0,1] & arr1[1,1] as elements

[2 7]


In [10]:
print(arr1[0:2,1:3]) #From both elements, slice index from 1 to 3(not included)

[[2 3]
 [7 8]]
