In [1]:
import numpy as np

In [2]:
b=np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

# Accessing array elements

In [5]:
print(b[0],b[1])   #Accessing 1st & 2nd element of array b

1 2


In [7]:
print(c[0])     #Accessing 1st row

[1 2 3]


In [8]:
print(c[1,1])   #Accessing 2nd element of 2nd row

5


In [10]:
print(d[0])    #Accessing 1st element in 1st dimension which is 2-D array

[[1 2 3]
 [4 5 6]]


In [11]:
print(d[0,1])  #Accessing the 1st & 2nd dimension which is 1-D array

[4 5 6]


In [12]:
print(d[0,1,2]) #Accessing the 1st, 2nd & 3rd dimension which is a single element

6


# Negative Indexing

In [14]:
print(c[1,-1])  #Accessing the last element of 2nd row

6


In [15]:
print(d[-1,-1,-2])

11
