In [1]:
import numpy as np

# Array Slicing

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [3]:
print(a[1:5])  #slice array from index 1 to index 4

[2 3 4 5]


In [4]:
print(a[1:])   #slice from index 1 till end of array

[2 3 4 5 6 7 8 9]


In [5]:
print(a[:6])   #slice from starting till index 5

[1 2 3 4 5 6]


In [7]:
print(a[::2])  #slice from 0th index till last index by taking 2 steps

[1 3 5 7 9]


# Negative slicing

In [8]:
print(a[-4:-1])  #slicing from 4th last element till 2nd last element

[6 7 8]


# Slicing in 2-D array

In [9]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [11]:
print(arr[1,1:4])   #From 2nd element, access elements from 1st to 3rd index

[7 8 9]


In [12]:
print(arr[:,2]) #Access 2nd element from all row

[3 8]


In [13]:
print(arr[:,1:4])  #Returns a 2-D array containing list of elements from index 1 to index 3

[[2 3 4]
 [7 8 9]]
