# Array Copy vs View

**Copy**

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])
x=arr.copy()
arr[0]=6

In [3]:
print(arr)
print(x)

[6 2 3 4]
[1 2 3 4]


**View**

In [4]:
viewarr=arr.view()
arr[0]=1

In [8]:
print(arr)
print(viewarr) #Changes in original array affect view

[6 2 3 4]
[6 2 3 4]


In [6]:
viewarr[0]=6

In [7]:
print(arr)
print(viewarr) #Changes in view affect original array

[6 2 3 4]
[6 2 3 4]


**Check if Array Owns its Data**

In [9]:
arr=np.array([1,2,3,4,5,6])
copyarr=arr.copy()
viewarr=arr.view()

In [11]:
print(copyarr.base) #As base attribute return None, so copy owns the data
print(viewarr.base)

None
[1 2 3 4 5 6]
