# Importing Numpy

In [2]:
import numpy as np            #aliasing as np

In [12]:
print(np.__version__)                 #checking version of numpy

1.20.3


In [3]:
arr=np.array([1,2,3,4,5])        #Creation of ndarray by passing list

In [4]:
print(arr)

[1 2 3 4 5]


In [14]:
print(type(arr[0]))               #type of array element is 32 bit integer

<class 'numpy.int32'>


In [13]:
print(type(arr))                  #type of array is 'numpy.ndarray'

<class 'numpy.ndarray'>


In [8]:
arr1=np.array([1,2,3,4,'a'])          #Accept element of different type

In [9]:
print(arr1)

['1' '2' '3' '4' 'a']


In [10]:
print(type(arr1[0]))                  #But changes type of all elements into single type

<class 'numpy.str_'>


In [15]:
tup1=(1,2,3,'a')

In [16]:
print(type(tup1))

<class 'tuple'>


In [17]:
print(type(tup1[0]),type(tup1[3]))

<class 'int'> <class 'str'>


In [18]:
arr2=np.array(tup1)

In [19]:
print(arr2)

['1' '2' '3' 'a']


In [20]:
print(type(arr2))

<class 'numpy.ndarray'>


# Dimensions of Arrays

In [26]:
a=np.array(42)
print(a)

42


In [27]:
b=np.array([1,2,3])
print(b)

[1 2 3]


In [28]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [29]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [25]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)        #Checking dimension of arrays

0
1
2
3
